### ISSUE TITLE
Improve API resourcedocs / swagger for PSD2 APIs

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#199]
Improve the specification coverage for PSD2 APIs

https://apiexplorersandbox.openbankproject.com/?version=2.1.0&psd2=true

So far: "Codes 200/400 are represented by only success and a missing "error" struct. Is it possible to get any further information on the types returned for each API."

**Comment by hongwei1** [comment]
fixed in #511

**Comment by chackett** [comment]
Hi @hongwei1 thanks for responding to this.

Can you please outline has this has been fixed? From the above link I click on the Swagger docs at the very bottom. Previously that link brought me to a HTML page where I could view the documentation but now just returns a bunch of JSON. When I inspect that JSON I still see the responses are just 200 / 400 and the error schema is still missing.

FYIL This is the link I refer to which was previously HTML documentation:

https://apisandbox.openbankproject.com/obp/v1.4.0/resource-docs/v2.1.0/swagger?core=&psd2=true&obwg=

**Comment by chackett** [comment]
Perhaps I am browsing an endpoint that does not yet have this release deployed?

**Comment by hongwei1** [comment]
@chackett 
Thanks for your message. Yes, the commit have not deployed on https://apisandbox.openbankproject.com server.

**Comment by sebtesobe** [comment]
@chackett The latest version of the API has been deployed to that server. Please check if your issue has been resolved.

**Comment by chackett** [comment]
Hi guys - It would appear that things have not changed. I still get a bunch of JSON back.

**Comment by hongwei1** [comment]
@chackett 

try this link:
https://apisandbox.openbankproject.com/obp/v1.4.0/resource-docs/v3.0.0/swagger?core=&psd2=&obwg=

**Comment by chackett** [comment]
Thanks guys. I think this is still broken. There are a number of issues.

* Way back in October I was at a OBP hackathon and clicking that link yielded a Swagger UI to browse the API documentation. Now it seems that is replaced by just a bunch of JSON. I was hoping to get a UI to enable me to browse the UI.
* This bug relates to the lack of any meaningful response messages in the documentation, making it difficult for me to write a wrapper. Also the error struct is still missing. In the JSON from those links: ""$ref": "#/definitions/BanksJSON"" still exists.

**Comment by hongwei1** [comment]
@chackett 
1 you can copy the Swagger JSON to http://editor.swagger.io/#/
2 we have provide the success body and error body as following :

"responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/BanksJSON"
            }
          },
          "400": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/ErrorUnKnownError"
            }
          }
        }

what's wrong on "$ref": "#/definitions/BanksJSON""? They are the Swagger grammar stuff.

Would you like to join our slack ? We can support you immediately there. 
https://openbankproject.slack.com/messages  
or https://slack.openbankproject.com/
